# Generated by Django 2.2.3 on 2019-08-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupPid', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=100, unique=True)),
                ('GroupPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('Nickname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('SubstitutePid', models.AutoField(primary_key=True, serialize=False)),
                ('Requestor', models.CharField(max_length=100)),
                ('Responsor', models.CharField(blank=True, max_length=100, null=True)),
                ('GroupPid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
    ]
