# Generated by Django 2.2.3 on 2019-07-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190729_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='GroupPid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='SubstitutePid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
