# Generated by Django 2.2.3 on 2019-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20190730_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='member_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
