# Generated by Django 2.2.3 on 2019-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190731_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='GroupPassword',
            field=models.CharField(max_length=100),
        ),
    ]
