# Generated by Django 2.2.3 on 2019-08-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('SchedulePid', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('StartHour', models.IntegerField()),
                ('StartMinute', models.IntegerField()),
                ('EndHour', models.IntegerField()),
                ('EndMinute', models.IntegerField()),
                ('GroupPid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('Nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Participate')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
